name: wear_pro
description: Final Year Project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  firebase_core: ^1.9.0
  firebase_auth: ^3.1.5
  cloud_firestore: ^3.0.0
  firebase_storage: ^10.2.5
  provider: ^6.0.1
  animated_bottom_navigation_bar: ^0.3.2
  badges: ^2.0.1
  carousel_slider: ^4.0.0
  animated_theme_switcher: ^2.0.1-nullsafety.0
  animated_radial_menu: ^0.0.1
  responsive_table: ^0.1.1+8
  data_tables: ^1.4.0
  data_table_2: 2.2.0
  fl_chart: ^0.40.2
  modal_progress_hud: ^0.1.3
  geolocator: ^8.0.0
  image_picker: ^0.8.4+9
  email_validator: ^2.0.1
  location: ^4.3.0
  geocoder: ^0.2.1
  flutter_easyloading: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
